### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by thetonus** [ryerkerk/rl_hockey#1]
How long did it take for you to train the agents?

**Comment by ryerkerk** [comment]
The included agent for the Hockey1v1 world was trained for roughly 48 hours on an i5/2060. The Hockey1v1Heuristic world should train a bit quicker than that. The 2v2 worlds remain a work in progress.

**Comment by thetonus** [comment]
I have been trying to create an RL agent for air hockey, and I haven't seen anyone actually implement anything remotely close. Nice to see your project do well.
